// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprFc7J34LdzP9P9qCnMrhzTsHQPoCW9g',
    appId: '1:750226609744:web:4e8111faa8845130b06355',
    messagingSenderId: '750226609744',
    projectId: 'authtutorial-ba5fb',
    authDomain: 'authtutorial-ba5fb.firebaseapp.com',
    storageBucket: 'authtutorial-ba5fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmEzYHfrz0ab7lMRfozFqr6Pr4KZKQQw',
    appId: '1:750226609744:android:b6ee4bcf96b9d606b06355',
    messagingSenderId: '750226609744',
    projectId: 'authtutorial-ba5fb',
    storageBucket: 'authtutorial-ba5fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hm4V7NYDtcCGrsyE9ifPdh_L4cV12xI',
    appId: '1:750226609744:ios:96044e04cec8deedb06355',
    messagingSenderId: '750226609744',
    projectId: 'authtutorial-ba5fb',
    storageBucket: 'authtutorial-ba5fb.appspot.com',
    iosClientId: '750226609744-99jc6kid3s85gids2kvmg42rt9kebtoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hm4V7NYDtcCGrsyE9ifPdh_L4cV12xI',
    appId: '1:750226609744:ios:96044e04cec8deedb06355',
    messagingSenderId: '750226609744',
    projectId: 'authtutorial-ba5fb',
    storageBucket: 'authtutorial-ba5fb.appspot.com',
    iosClientId: '750226609744-99jc6kid3s85gids2kvmg42rt9kebtoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
